Saving

diff --git a/hyakvnc-freesurfer-ubuntu22.04/Singularity b/hyakvnc-freesurfer-ubuntu22.04/Singularity
--- a/hyakvnc-freesurfer-ubuntu22.04/Singularity
+++ b/hyakvnc-freesurfer-ubuntu22.04/Singularity
@@ -1,23 +1,27 @@
 Bootstrap: {{BOOTSTRAP_SOURCE}}
-From: {{BOOTSTRAP_FROM}}
+From: {{BOOTSTRAP_FROM_REPO}}/hyakvnc-vncserver-ubuntu22.04{{BOOTSTRAP_FROM_SUFFIX}}
 
 %arguments
 	BOOTSTRAP_SOURCE=localimage
-	BOOTSTRAP_FROM=../hyakvnc-vncserver-ubuntu22.04.sif
+	BOOTSTRAP_FROM_REPO=..
+	BOOTSTRAP_FROM_SUFFIX=.sif
 	FREESURFER_VERSION=7.4.1
 	FREESURFER_URL=https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/{{FREESURFER_VERSION}}/freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
-	FREESURFER_DOWNLOAD_FILENAME=freesurfer.deb
+	FREESURFER_DOWNLOAD_FILENAME=freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb
 
 %setup
+	
 	if ! [ -r "{{FREESURFER_DOWNLOAD_FILENAME}}" ]; then
-		command -v curl >/dev/null 2>&1 || { echo "warning: curl not found!" >&2; exit 1; }		
+		command -v curl >/dev/null 2>&1 || { echo "warning: curl not found!" >&2; exit 1; }
+		trap 'rm -f "tmp-{{FREESURFER_DOWNLOAD_FILENAME}}"' INT TERM HUP EXIT TSTP
 		curl --fail --fail-early --compressed --location \
 			--continue-at - \
-			--output "{{FREESURFER_DOWNLOAD_FILENAME}}" \
+			--output "tmp-{{FREESURFER_DOWNLOAD_FILENAME}}" \
 			"{{FREESURFER_URL}}" || { echo "warning: curl failed!" >&2; exit 1; }
 		echo "Downloaded {{FREESURFER_DOWNLOAD_FILENAME}} from {{FREESURFER_URL}}."
+		mv -v "tmp-{{FREESURFER_DOWNLOAD_FILENAME}}" "{{FREESURFER_DOWNLOAD_FILENAME}}"
 	fi
-	ln -v "{{FREESURFER_DOWNLOAD_FILENAME}}" "${APPTAINER_ROOTFS}/{{FREESURFER_DOWNLOAD_FILENAME}}" || { echo "warning: ln failed!" >&2; exit 1; }
+	ln -v "{{FREESURFER_DOWNLOAD_FILENAME}}" "${APPTAINER_ROOTFS}/freesurfer.deb" || { echo "warning: ln failed!" >&2; exit 1; }
 	
 	if command -v git >/dev/null 2>&1 && git tag 2>/dev/null; then
 		IMAGE_VCS_URL="${IMAGE_VCS_URL:-$(git config --get remote.origin.url || true)}"
@@ -66,7 +70,7 @@ From: {{BOOTSTRAP_FROM}}
 
 %post
 	set -e
-	ls -l /{{FREESURFER_DOWNLOAD_FILENAME}}
-	#dpkg --install /{{FREESURFER_DOWNLOAD_FILENAME}}
-	unlink /{{FREESURFER_DOWNLOAD_FILENAME}}
+	du -h /freesurfer.deb
+	dpkg --install /freesurfer.deb
+	unlink /freesurfer.deb
 
