Updated interactive image

diff --git a/ubuntu22.04_interactive/Singularity b/ubuntu22.04_interactive/Singularity
--- a/ubuntu22.04_interactive/Singularity
+++ b/ubuntu22.04_interactive/Singularity
@@ -8,14 +8,14 @@ From: ubuntu:22.04
 	Maintainer altan@uw.edu
 
 %environment
-	export DEBIAN_FRONTEND=noninteractive
 	export LANG=C.UTF-8
 	export LC_ALL=C.UTF-8
 	export TZ=America/Los_Angeles
 
 %post
-	set -e
-	set -x
+	set -e # Exit on error
+	set -o pipefail # Exit on pipe error
+	set -x # Print commands as they are executed
 	export DEBIAN_FRONTEND=noninteractive
 	export TZ='America/Los_Angeles'
 	export LANG=C.UTF-8
@@ -28,10 +28,9 @@ From: ubuntu:22.04
 		touch /var/lib/locales/supported.d/$localename && \
 		chmod a-r /var/lib/locales/supported.d/$localename
 	done
-
+	
 	# We want man pages:
 	echo Y | unminimize
-	
 	
 	# Update package list:
 	apt-get update -qq
@@ -40,7 +39,6 @@ From: ubuntu:22.04
 	# apt-utils: for apt utilities
 	# bash-completion: for bash completion of commands
 	# curl: for downloading files
-	# debconf: for debconf to manage packages
 	# findutils: for find, xargs, etc. to find files
 	# gawk: for awk to process text files
 	# git: for git to manage source code
@@ -48,22 +46,24 @@ From: ubuntu:22.04
 	# less: for less to view files
 	# locales: for localedef to install locales
 	# make: for make to build things
+	# man: for man pages
+	# man-db: for man pages
 	# nano: for nano to edit files
 	# net-tools: for ifconfig, netstat, etc. to manage network
 	# netcat-openbsd: for nc, etc. to work with network connections
 	# openssh-client: for ssh and scp to connect to other machines
 	# procps: for ps, top, etc. to manage processes
 	# psmisc: for killall, etc. to manage processes
-	# python3: for python3 to run python scripts
-	# python3-pip: for pip3 to install python packages
-	# python3-setuptools: for easy_install3 to install python packages
-	# python3-venv: for python3 -m venv to create virtual environments
-	# python3-wheel: support bdist_wheel for python packages
+	# python3-full: for python3 to run scripts
 	# vim: for vim to edit files
-	# wget: for wget to download files
-	apt-get install --yes --quiet --no-install-recommends \
+	# xz-utils: for xz to uncompress files
+	# zip: for zip to compress files
+
+	apt-get install --yes --quiet \
 		apt-utils \
 		bash-completion \
+		bash-doc \
+		bzip2 \
 		curl \
 		findutils \
 		gawk \
@@ -74,20 +74,18 @@ From: ubuntu:22.04
 		make \
 		man \
 		man-db \
-		manpages-posix \
 		nano \
 		net-tools \
 		netcat-openbsd \
 		openssh-client \
+		socat \
 		procps \
 		psmisc \
-		python3 \
-		python3-pip \
-		python3-setuptools \
-		python3-venv \
-		python3-wheel \
-		vim
-		
+		python3-full \
+		vim \
+		xz-utils \
+		zip
+
 	# Install en_US.UTF-8 locale:
 	localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
 
